# add binding for reloading this config
bind R source-file ~/.config/tmux/tmux.conf

# Change the default $TERM to tmux-256color
set -g default-terminal "tmux-256color"

# Enable RGB colour if running in xterm(1)
set -ga terminal-overrides ",xterm-256color:Tc"

set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'  # undercurl support
set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'  # underscore colours - needs tmux-3.0

# Disable copy mode dragging with the mouse
unbind -n MouseDrag1Pane
unbind -Tcopy-mode MouseDrag1Pane

# Whether focus key sequences are sent by tmux when the active pane changes
# and when received from the outside terminal if it supports them
set-option -g focus-events on

# open new panes/windows in same directory
bind c new-window -c "#{pane_current_path}"
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# Align the status bar to the top and enable toggling
set-option -g status-position top
bind-key b set-option status

# Respond to dark/light mode
if-shell -F "#{==:#{client_theme},light}" {
	run 'sh ~/.config/tmux/theme-scripts/activate-flexoki-light.sh'
} {
	run 'sh ~/.config/tmux/theme-scripts/activate-flexoki-dark.sh'
}

set-hook -g client-light-theme 'run "sh ~/.config/tmux/theme-scripts/activate-flexoki-light.sh"'
set-hook -g client-dark-theme 'run "sh ~/.config/tmux/theme-scripts/activate-flexoki-dark.sh"'
